In [1]:
'''
python 数学编程&物理建模
'''
print('hello world!')

hello world!


第一章 python入门

In [1]:
import numpy as np#调用整个库，时间非常久
np.sqrt(2)

1.4142135623730951

In [2]:
from numpy import exp
exp(1)

2.718281828459045

In [3]:
from numpy.random import random as rnf#0-1随机数生成器
rnf()

0.6313933246615623

第二章 数据结构和程序控制

In [4]:
n=11.0
n.is_integer()

True

In [5]:
s='TrustMe'
s.swapcase()

'tRUSTmE'

In [7]:
L=[1,2,3,4]
L.reverse()
print(L)

[4, 3, 2, 1]


In [8]:
L.pop(2)

2

In [2]:
import numpy
a=numpy.zeros(4)
print(a)

[0. 0. 0. 0.]


In [13]:
a=numpy.zeros((3,5))#三行五列
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
b=numpy.ones((5,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
e=numpy.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
e=numpy.eye(4, k=1)
print(e)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [19]:
f=numpy.ones((4, 1))
g=numpy.ones((1, 4))
print(f, g)

[[1.]
 [1.]
 [1.]
 [1.]] [[1. 1. 1. 1.]]


In [20]:
A = np.zeros((2, 3, 4))
print(A)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
a20 = np.zeros(2,3)#需要两个括号
print(a20)

TypeError: data type not understood

In [21]:
numpy.shape(A)

(2, 3, 4)

In [22]:
numpy.size(A)

24

In [26]:
Ar = numpy.array([[2, 3, 4],[3, 4, 5]])
print(Ar)

[[2 3 4]
 [3 4 5]]


In [27]:
Ar.sum()#求和

21

In [29]:
Ar.mean()#平均值

3.5

In [30]:
Ar.std()#标准差

0.9574271077563381

In [31]:
lista = [1, 2, 3, 4]#这是列表，不是Numpy的数组对象
lista.sum()

AttributeError: 'list' object has no attribute 'sum'

In [32]:
A31 = numpy.arange(1, 10)#有头无尾
print(A31)

[1 2 3 4 5 6 7 8 9]


In [37]:
A32 = numpy.arange(10)#和python自带的range函数不一样
print(A32)
a32 = range(10)
print(a32)
A31a = numpy.arange(1, 4, 0.7)#有头无尾
print(A31a)

[0 1 2 3 4 5 6 7 8 9]
range(0, 10)
[1.  1.7 2.4 3.1 3.8]


In [42]:
a38 = numpy.arange(0, 10, 2)
b38 = numpy.linspace(0, 10, 6)
print(a38, b38)

[0 2 4 6 8] [ 0.  2.  4.  6.  8. 10.]


In [43]:
a39 = numpy.arange(0, 10, 1.5)
b39 = numpy.linspace(0, 10, 7)
print(a39, b39)

[0.  1.5 3.  4.5 6.  7.5 9. ] [ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


In [13]:
a = np.zeros((2, 3))
b = np.ones((2, 3))
h = np.hstack([a, b])
v = np.vstack([a, b])
print(h)
print('\n')
print(v)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
A = np.array([2, 3, 4])#访问数组元素
A[0]=100
print(A)

[100   3   4]


In [4]:
A = np.array([[2, 3, 5], [7, 11, 13]])
print(A)
print(A[0])
print(A[0][1])

[[ 2  3  5]
 [ 7 11 13]]
[2 3 5]
3


In [5]:
aa = np.array([[1, 2], [3, 4, 5]])#不是矩阵的情况
print(aa)

[list([1, 2]) list([3, 4, 5])]


In [6]:
A[1][1] = 999
print(A)

[[  2   3   5]
 [  7 999  13]]


In [7]:
A[1] = 999 #numpy.py中，A[1]是A__getitem__(1)的缩写；A[1]=999是A__setitem__(1,999)的缩写
print(A)

[[  2   3   5]
 [999 999 999]]


python中的变量是指向数据储存空间的，列表A=B是将A和B同事指向列表B。所以python的列表复制一定要用克隆的方法 A=B[:]

In [8]:
a = 1
b = a
b = 2
print(a, b)

1 2


In [9]:
A = np.zeros(3)
B = A
A[0] = 3
B[1] = 4
print(A, B)

[3. 4. 0.] [3. 4. 0.]


In [29]:
A = np.zeros(3)
A[0] = 3
B = A[:]
B[1] = 4
print(A, B)

[3. 4. 0.] [3. 4. 0.]


In [18]:
A = 1 #A = 1使A被python认为是整数
A[0] = 1

TypeError: 'int' object does not support item assignment

In [23]:
A = [1, 3, 4]
A = 3
print(A)

3


In [24]:
N = np.size(A)
print(N)

1


In [26]:
B = np.zeros(5)
N = np.size(B)
print(B, N)

[0. 0. 0. 0. 0.] 5


In [28]:
x = B[0: N: 1] #切片方法 【起始值：终止值：幅度】
y = B[1: N: 1]
print(x, y)

[0. 0. 0. 0. 0.] [0. 0. 0. 0.]


In [32]:
a = np.arange(20)
print(a[:],a[::])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [35]:
print(a[5: 15], a[5: 16: 3])

[ 5  6  7  8  9 10 11 12 13 14] [ 5  8 11 14]


In [39]:
print(a[5:])#print(a[5::])一样
print(a[:5])#print(a[：5:])一样
print(a[::5])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4]
[ 0  5 10 15]


In [40]:
a[0:3] = np.ones(3) #修改前三个数值
print(a)

[ 1  1  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


数组展平;改变数组形状；索引

In [42]:
a = np.array([[1, 2],[3, 4]])
b = a.flatten()#返回一个独立的数组
print(a, b)

[[1 2]
 [3 4]] [1 2 3 4]


In [45]:
c = np.ravel(a)
d = a.ravel()#访问对象还是在a上
print(c, d)
print(a)

[1 2 3 4] [1 2 3 4]
[[1 2]
 [3 4]]


In [46]:
b[1] = 11
print(a)

[[1 2]
 [3 4]]


In [47]:
c[1] = 12 #c指向a只是形状不同，这可以用来解决一些二位数组的问题
print(a)

[[ 1 12]
 [ 3  4]]


In [52]:
a = np.arange(12)
b = np.reshape(a, (3, 4))
c = b.reshape((2, 6))
d = c.reshape((2, 3, 2))
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [53]:
c[1][1] = 999 #只改变形状，不生成新数组
print(a)

[  0   1   2   3   4   5   6 999   8   9  10  11]


In [54]:
a = np.arange(10, 21)
b = [2, 4, 5]
print(a[b])

[12 14 15]


In [55]:
less_than_fifteen = (abs(a)< 15)#这是一个布尔型的数组
b = a[less_than_fifteen]
print(less_than_fifteen)
print(b)

[ True  True  True  True  True False False False False False False]
[10 11 12 13 14]


In [56]:
print(a[abs(a)< 15])

[10 11 12 13 14]


字符串

In [57]:
print("let's go!")
print('let\'s go!')#转义字符

let's go!
let's go!


In [60]:
s = 'hello'
t = 'world'
print(4*s)
print(s+t)
print(s+' '+t)

hellohellohellohello
helloworld
hello world


In [68]:
num = 80
s ='$='+str(num)
print(s)

$=80


In [69]:
# string_format.py  
# -------------------------------------------------------------------------
# Illustrate formatting strings using the .format() method.
# ------------------------------------------------------------------------- 
import numpy as np

print("The value of pi is approximately " + str(np.pi))
print("The value of {} is approximately {:.5f}".format('pi', np.pi))#.5f五位的浮点数
#{}表示format要插入的位置，‘：’表示后面是一个格式化的命令
s = "{1:d} plus {0:d} is {2:d}"#d表示十进制
print(s.format(2,4,2+4))

print("Every {2} has its {3}.".format('dog','day','rose','thorn'))#{}里的数字是导入第几个不写就按顺序
print("The third element of the list is {0[2]:g}.".format(np.arange(10)))#这里引入了数组，g表示通用general，用最少的字符表示一个数字


The value of pi is approximately 3.141592653589793
The value of pi is approximately 3.14159
4 plus 2 is 6
Every rose has its thorn.
The third element of the list is 2.


In [71]:
# string_percent.py  
# -------------------------------------------------------------------------
# Illustrate string formatting using the % method.
# ------------------------------------------------------------------------- 
import numpy as np

print("The value of pi is approximately " + str(np.pi))
print("The value of %s is approximately %.5f" % ('pi', np.pi))

s = "%d plus %d is %d"
print(s % (2, 4, 2 + 4))


The value of pi is approximately 3.141592653589793
The value of pi is approximately 3.14159
2 plus 4 is 6


In [84]:
d = 2
print(5%d)
print('5%d'%2 )

1
52
