In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
c = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]])
print(c)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [5]:
c.dtype

dtype('int32')

In [6]:
c.shape

(3, 4)

In [7]:
c

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [11]:
c.shape = 4, 3
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [12]:
#不想算具体元素，可以设为-1
c.shape = 2,-1
c

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

In [14]:
#不改变原数组的话可以用reshape方法
d = a.reshape((2, 2))
print(a)
print(d)

[1 2 3 4]
[[1 2]
 [3 4]]


In [15]:
#注意a d共享内存存储空间
a[1] = 100
d

array([[  1, 100],
       [  3,   4]])

In [16]:
np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]], dtype=np.float)

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [ 7.,  8.,  9., 10.]])

In [17]:
np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]], dtype=np.complex)

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j]])

In [18]:
np.arange(0,1,0.1)#生产数组

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [19]:
np.linspace(0, 1, 12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [20]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [3]:
s = 'abcdefgh'
np.fromstring(s, dtype = np.int8 )

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


array([ 97,  98,  99, 100, 101, 102, 103, 104], dtype=int8)

In [5]:
def func(i):
    return i%4 + 1
np.fromfunction(func, (10,))

array([1., 2., 3., 4., 1., 2., 3., 4., 1., 2.])

In [7]:
def func2(i, j):
    return (i+1)*(j+1)
np.fromfunction(func2,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [8]:
a = np.arange(10)
a[5]

5

In [9]:
a[3:5]

array([3, 4])

In [10]:
a[:5]

array([0, 1, 2, 3, 4])

In [11]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
a[2:4] = 100, 101
a

array([  0,   1, 100, 101,   4,   5,   6,   7,   8,   9])

In [14]:
a[::-1]

array([  9,   8,   7,   6,   5,   4, 101, 100,   1,   0])

In [15]:
b = a[:]#列表克隆问题
b[1] = 10
a

array([  0,  10, 100, 101,   4,   5,   6,   7,   8,   9])

In [16]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [17]:
x[[3, 1, 1, 8]]

array([7, 9, 9, 2])

In [18]:
b = x[[-1, -2, -4]]
b

array([2, 3, 5])

In [19]:
b[2] = 100
b

array([  2,   3, 100])

In [20]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [21]:
x[[2,3,6]] = -1, -2, -3
x

array([10,  9, -1, -2,  6,  5, -3,  3,  2])

In [22]:
x = np.arange(5, 0, -1)
x

array([5, 4, 3, 2, 1])

In [23]:
x[np.array([True, False, True, False, False])]

array([5, 3])

In [25]:
x = np.random.rand(10)
x

array([0.23700894, 0.17065171, 0.88334311, 0.53394848, 0.54002816,
       0.88332515, 0.47994049, 0.64962625, 0.38765054, 0.15413771])

In [26]:
x > 0.5

array([False, False,  True,  True,  True,  True, False,  True, False,
       False])

In [27]:
x[x>0.5]

array([0.88334311, 0.53394848, 0.54002816, 0.88332515, 0.64962625])

In [30]:
a = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [31]:
a[0, 3:5]

array([3, 4])

In [33]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [34]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [35]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [36]:
a[(0,2,4),(1,2,3)]

array([ 1, 22, 43])

In [37]:
a[3:,[0,2,3]]

array([[30, 32, 33],
       [40, 42, 43],
       [50, 52, 53]])

In [39]:
persontype = np.dtype({'names':['name', 'age', 'weight'],\
'formats':['S32','i', 'f']})
a = np.array([("Zhang",32,75.5),("Wang",24,65.2)],\
dtype=persontype)
a

array([(b'Zhang', 32, 75.5), (b'Wang', 24, 65.2)],
      dtype=[('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

In [40]:
a.dtype

dtype([('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

In [41]:
'''类型描述前面为我们添加了`|', `<' 等字符，这些字符用来描述字
段值的字节顺序：
• | : 忽视字节顺序
• < : 低位字节在前
• > : 高位字节在前
'''
a[0]

(b'Zhang', 32, 75.5)

In [42]:
x = np.linspace(0, 2*np.pi, 10)
y = np.sin(x)
y

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [43]:
t = np.sin(x, x)
x

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [44]:
id(t) == id(x)

True

In [49]:
import time
import math
import numpy as np
x = [i * 0.001 for i in range(1000)]
start = time.clock()
for i, t in enumerate(x):
    x[i] = math.sin(t)
print("math.sin:{}", time.clock() - start)
x = [i * 0.001 for i in range(1000)]
x = np.array(x)
start = time.clock()
np.sin(x,x)
print("numpy.sin:{}", time.clock() - start)

math.sin:{} 0.0005130999998073094
numpy.sin:{} 0.0002783999998428044


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """
D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # This is added back by InteractiveShellApp.init_path()
D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  del sys.path[0]


In [50]:
a = np.arange(0,4)
b = np.arange(1,5)
np.add(a,b)

array([1, 3, 5, 7])

In [51]:
np.add(a,b,a)
a

array([1, 3, 5, 7])

In [2]:
import numpy as np
persontype = np.dtype({
    'names':['name', 'age', 'weight'],
    'formats':['S32','i', 'f']})
a = np.array([("Zhang",32,75.5),("Wang",24,65.2)],
    dtype=persontype)

In [3]:
a.dtype

dtype([('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

In [4]:
a[0]

(b'Zhang', 32, 75.5)

In [5]:
a[0].dtype

dtype([('name', 'S32'), ('age', '<i4'), ('weight', '<f4')])

In [6]:
#a[0]是一个结构元素，它和数组a共享内存数据，因此可以通过修改它的字段，改变原始数组中的对应字段：
c = a[1]
c["name"] = "Li"
a[1]["name"]

b'Li'

In [7]:
#结构像字典一样可以通过字符串下标获取其对应的字段值：
a[0]["name"]

b'Zhang'

In [8]:
b = a[:]['age']
b

array([32, 24], dtype=int32)

In [9]:
def triangle_wave(x, c, c0, hc):
    x = x - int(x) # 三角波的周期为1，因此只取x坐标的小数部分进行计算
    if x >= c: r = 0.0
    elif x < c0: r = x / c0 * hc
    else: r = (c-x) / (c-c0) * hc
    return r

In [10]:
x = np.linspace(0, 2, 1000)
y = np.array([triangle_wave(t, 0.6, 0.4, 1.0) for t in x])

In [11]:
triangle_ufunc = np.frompyfunc( lambda x: triangle_wave(x, 0.6, 0.4, 1.0), 1, 1)
y2 = triangle_ufunc(x)
'''frompyfunc的调用格式为frompyfunc(func, nin, nout)，
其中func是计算单个元素的函数，nin是此函数的输入参数的个数，
nout是此函数的返回值的个数。
虽然triangle_wave函数有4个参数，
但是由于后三个c, c0, hc在整个计算中值都是固定的，
因此所产生的ufunc函数其实只有一个参数。
为了满足这个条件，我们用一个lambda函数对triangle_wave的参数进行一次包装。
这样传入frompyfunc的函数就只有一个参数了。
这样子做，效率并不是太高，另外还有一种方法：'''

In [12]:
def triangle_func(c, c0, hc):
    def trifunc(x):
        x = x - int(x) # 三角波的周期为1，因此只取x坐标的小数部分进行计算
        if x >= c: r = 0.0
        elif x < c0: r = x / c0 * hc
        else: r = (c-x) / (c-c0) * hc
        return r

    # 用trifunc函数创建一个ufunc函数，可以直接对数组进行计算, 不过通过此函数
    # 计算得到的是一个Object数组，需要进行类型转换
    return np.frompyfunc(trifunc, 1, 1)

y2 = triangle_func(0.6, 0.4, 1.0)(x)

In [14]:
a = np.arange(0, 60, 10).reshape(-1, 1)
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [15]:
a.shape

(6, 1)

In [16]:
b = np.arange(0, 5)
b

array([0, 1, 2, 3, 4])

In [17]:
b.shape

(5,)

In [18]:
c = a + b
c

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [19]:
c.shape

(6, 5)

In [20]:
b = b.repeat(6,axis=0)
b

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4])

In [22]:
b = np.arange(0, 5)
b.shape = 1,5#reshape(1,5)
b = b.repeat(6,axis=0)
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [25]:
a = np.arange(0, 60, 10).reshape(-1, 1)
a = a.repeat(5, axis=1)
a

array([[ 0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50]])

In [26]:
x,y = np.ogrid[0:5,0:5]
x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [27]:
y

array([[0, 1, 2, 3, 4]])

In [28]:
>>> x, y = np.ogrid[0:1:4j, 0:1:3j]
>>> x

array([[0.        ],
       [0.33333333],
       [0.66666667],
       [1.        ]])

In [29]:
y#开始值:结束值:长度j，当第三个参数为虚数时，它表示返回的数组的长度，和np.linspace(开始值, 结束值, 长度)类似：

array([[0. , 0.5, 1. ]])

In [32]:
np.add.reduce([1,2,3]) 

6

In [33]:
np.add.reduce([[1,2,3],[4,5,6]], axis=1) # 1,4 + 2,5 + 3,6

array([ 6, 15])

In [34]:
np.add.accumulate([1,2,3])

array([1, 3, 6], dtype=int32)

In [35]:
np.add.accumulate([[1,2,3],[4,5,6]], axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [36]:
a = np.array([1,2,3,4])
result = np.add.reduceat(a,indices=[0,1,0,2,0,3,0])
result

array([ 1,  2,  3,  3,  6,  4, 10], dtype=int32)

In [37]:
np.multiply.outer([1,2,3,4,5],[2,3,4])

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16],
       [10, 15, 20]])

In [38]:
a = np.matrix([[1,2,3],[5,5,6],[7,9,9]])

In [39]:
a*a

matrix([[ 32,  39,  42],
        [ 72,  89,  99],
        [115, 140, 156]])

In [40]:
a**-1

matrix([[-0.6       ,  0.6       , -0.2       ],
        [-0.2       , -0.8       ,  0.6       ],
        [ 0.66666667,  0.33333333, -0.33333333]])